packages:
  - test-applications/cdn-apps/as/*
  - test-applications/http-apps/*

onlyBuiltDependencies:
  - esbuild

minimumReleaseAge: 4320 # 3 days
trustPolicy: no-downgrade
blockExoticSubdeps: true
strictDepBuilds: true
