/**
 * Legacy WASM binary detection
 *
 * DEPRECATED SUPPORT: This module detects legacy #[fastedge::http] sync WASM
 * binaries that require --wasi-http false. The async #[wstd::http_server]
 * pattern is the standard going forward. Once legacy sync binaries are fully
 * retired, this entire module can be deleted.
 *
 * Detection signal: legacy sync binaries export "process" (from the
 * gcore:fastedge/http-handler WIT interface). Modern async binaries export
 * "wasi:http/incoming-handler@*#handle" instead.
 */

import { readFile } from "fs/promises";

/**
 * Returns true if the WASM binary is a legacy sync #[fastedge::http] module.
 *
 * Inspects the binary's exports for the "process" function, which is the
 * entry point generated by the fastedge::http proc-macro. Async wstd binaries
 * and JS component-model binaries do NOT export "process".
 *
 * On any detection failure (e.g. component-model binary that can't be
 * compiled by Node's WebAssembly API), returns false — meaning the default
 * --wasi-http true path is used, which is correct for all non-legacy binaries.
 */
export async function isLegacySyncWasm(
  bufferOrPath: Buffer | string,
): Promise<boolean> {
  let buffer: Buffer;
  if (typeof bufferOrPath === "string") {
    buffer = await readFile(bufferOrPath);
  } else {
    buffer = bufferOrPath;
  }

  try {
    const module = await WebAssembly.compile(new Uint8Array(buffer));
    const exports = WebAssembly.Module.exports(module);
    return exports.some((exp) => exp.name === "process");
  } catch {
    // Component-model binaries (JS SDK) fail WebAssembly.compile().
    // These are always wasi-http compatible.
    return false;
  }
}
