name: Integration Tests

on:
  pull_request:
    branches: ["*.*.x", "*.x", "main", "next", "next-major", "beta", "alpha"]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node Environment
        uses: ./.github/setup-node

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-wasip1

      - name: Setup FastEdge Run CLI
        uses: ./.github/setup-fastedge-cli
        with:
          github_token: ${{ github.token }}

      - name: Build (including WASM test apps)
        run: pnpm run build:ci-test

      - name: Run tests
        run: pnpm test

  fossa:
    uses: ./.github/workflows/fossa.yaml
    secrets:
      FOSSA_PUB_API_KEY: ${{ secrets.FOSSA_PUB_API_KEY }}
